[theme]
primaryColor = "#274764"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F5F8"
textColor = "#24354B"
font = "sans serif"

[server]
headless = true
address = "127.0.0.1"
maxUploadSize = 2

[browser]
gatherUsageStats = false
